# Generated by Django 3.0.3 on 2020-11-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201103_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='testProduct'),
            preserve_default=False,
        ),
    ]
